version: "3.8"

services:

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db

  backend:
    container_name: backend_app
    build: ./backend
    command: bash -c "poetry run alembic upgrade head && poetry run uvicorn questionary.main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - ./backend:/app
    ports:
      - 8080:80
    depends_on:
      - db
