"""making genre_id optional

Revision ID: 5a654202b52f
Revises: f56bab450f92
Create Date: 2023-12-19 19:38:47.355301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5a654202b52f'
down_revision: Union[str, None] = 'f56bab450f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
